/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as HotelesIndexImport } from './routes/hoteles/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HotelesIndexRoute = HotelesIndexImport.update({
  id: '/hoteles/',
  path: '/hoteles/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/hoteles/': {
      id: '/hoteles/'
      path: '/hoteles'
      fullPath: '/hoteles'
      preLoaderRoute: typeof HotelesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hoteles': typeof HotelesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hoteles': typeof HotelesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/hoteles/': typeof HotelesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hoteles'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hoteles'
  id: '__root__' | '/' | '/hoteles/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HotelesIndexRoute: typeof HotelesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HotelesIndexRoute: HotelesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/hoteles/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/hoteles/": {
      "filePath": "hoteles/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
