/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as RoomsIndexImport } from './routes/rooms/index'
import { Route as HotelsIndexImport } from './routes/hotels/index'
import { Route as HotelsHotelIdImport } from './routes/hotels/$hotelId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RoomsIndexRoute = RoomsIndexImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRoute,
} as any)

const HotelsIndexRoute = HotelsIndexImport.update({
  id: '/hotels/',
  path: '/hotels/',
  getParentRoute: () => rootRoute,
} as any)

const HotelsHotelIdRoute = HotelsHotelIdImport.update({
  id: '/hotels/$hotelId',
  path: '/hotels/$hotelId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/hotels/$hotelId': {
      id: '/hotels/$hotelId'
      path: '/hotels/$hotelId'
      fullPath: '/hotels/$hotelId'
      preLoaderRoute: typeof HotelsHotelIdImport
      parentRoute: typeof rootRoute
    }
    '/hotels/': {
      id: '/hotels/'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsIndexImport
      parentRoute: typeof rootRoute
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/hotels': typeof HotelsIndexRoute
  '/rooms': typeof RoomsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/hotels': typeof HotelsIndexRoute
  '/rooms': typeof RoomsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/hotels/': typeof HotelsIndexRoute
  '/rooms/': typeof RoomsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hotels/$hotelId' | '/hotels' | '/rooms'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hotels/$hotelId' | '/hotels' | '/rooms'
  id: '__root__' | '/' | '/hotels/$hotelId' | '/hotels/' | '/rooms/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HotelsHotelIdRoute: typeof HotelsHotelIdRoute
  HotelsIndexRoute: typeof HotelsIndexRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HotelsHotelIdRoute: HotelsHotelIdRoute,
  HotelsIndexRoute: HotelsIndexRoute,
  RoomsIndexRoute: RoomsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/hotels/$hotelId",
        "/hotels/",
        "/rooms/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/hotels/$hotelId": {
      "filePath": "hotels/$hotelId.tsx"
    },
    "/hotels/": {
      "filePath": "hotels/index.tsx"
    },
    "/rooms/": {
      "filePath": "rooms/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
